algoritmo "Exercicio19"

var quantidadeF1, quantidadeF2, quantidadeF3: inteiro

inicio

   escreva("Digite a quantidade de latas (350ml): ")
   leia(quantidadeF1)
   
   escreva("Digite a quantidade de garrafas (600ml): ")
   leia(quantidadeF2)
   
   escreva("Digite a quantidade de garrafas (2l): ")
   leia(quantidadeF3)

   escreva("Quantidade em litros: ",quantidadeF1 * 0.350 + quantidadeF2 * 0.600 + quantidadeF3 * 2)

fimalgoritmo
